name: CD

on:
  push:
    branches: [ main ]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Run Super-Linter Against Source Code
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Checkout Node.js Image
        uses: actions/setup-node@v3
        with:
          node-version: 18.*
          cache: 'npm'
      - name: Run Tests Against Source Code
        run: |
          yarn install --frozen-lockfile
          yarn run test
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Checkout Node.js Image
        uses: actions/setup-node@v3
        with:
          node-version: 18.*
          cache: 'npm'
      - name: Deploy
        run: |
          yarn install --frozen-lockfile
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn run deploy
        env:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
