name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      - name: Checkout Node.js Image
        uses: actions/setup-node@v3
        with:
          node-version: 18.*
          cache: 'npm'
      - name: Deploy
        run: |
          yarn install --frozen-lockfile
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn run deploy
        env:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
