name: CI

on:
  push:
  pull_request:
    branches: [master, main]


jobs:
  super-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Calomodoro Source Code
        uses: actions/checkout@v3

      - name: Run Super-Linter Against Calomodoro Source Code
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_CSS: false
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_DOCKERFILE_HADOLINT:  false