name: CI

on:
  push:
  pull_request:
    branches: [master, main]


jobs:
  Lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Calomodoro Source Code
        uses: actions/checkout@v3

      - name: Run Super-Linter Against Calomodoro Source Code
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}