name: CI

on:
  push:
  pull_request:
    branches: [master, main]


jobs:
  super-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Calomodoro Source Code
        uses: actions/checkout@v3

      - name: Run Super-Linter Against Calomodoro Source Code
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}